apiVersion: v1
kind: ConfigMap
metadata:
  name: retailpulse-grafana-config
  namespace: retailpulse
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://retailpulse-prometheus.retailpulse.svc.cluster.local:9090
        isDefault: true
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: RetailPulse
        orgId: 1
        folder: RetailPulse
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
